language: node_js
node_js:
- '4'
sudo: false
cache:
  yarn: true
  directories:
  - "$HOME/.npm"
before_install:
- yarn config set spin false
- yarn install -g bower phantomjs-prebuilt
- bower --version
- phantomjs --version
install:
- yarn install
- bower install
script:
- yarn test
before_deploy: yarn build --environment production
deploy:
- provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: dist
  repo: parch-js/parch-js.github.io
  target_branch: master
  skip_cleanup: true
  on:
    branch: master
